### ISSUE TITLE
Scenarios where Macros are disabled.

### ISSUE THREAD

**Issue by ravibak** [Azure/review-checklists#118] opened 2022-02-08 02:23 UTC
Perhaps we could add a note that Macros are required and if customer dont allow or have it disabled, they could wait for web based version which is in progress ?

**Comment by erjosito** [comment] 2022-02-08 08:14
Hey @ravibak thanks for the feedback! I believe this one is a duplicate of #13 . There are two possible solutions that we are envisioning to solve this:

#11 : building a pipeline that generates macro-free workbooks. AFAIK nobody is working on this, if you have an idea feel free to contribute here
#14 : creating a web-based frontend that replaces the spreadsheet. We have a prototype of this in the `web` folder of this repo. We have on the roadmap the item to create a better version, but no ETA yet.

Do you see any other approach that I am missing? Otherwise, we can close this as a duplicate of #13 .

**Comment by erjosito** [comment] 2022-02-17 09:43
Closing as duplicate

**Closed by erjosito** 2022-02-17 09:43 UTC
Labels: duplicate
