### ISSUE TITLE
parse error: Invalid escape at line 285, column 436

### ISSUE THREAD

**Issue by sijday** [Azure/review-checklists#120] opened 2022-02-09 10:49 UTC
Hello, 
I am attempting to use checklist_graph.sh on a Linux VM and connecting to my tenant/subs using Azure CLI. 
When running the script the following error occurs:

parse error: Invalid escape at line 285, column 436

**Comment by erjosito** [comment] 2022-02-16 15:27
Hey @sijday thanks for logging the issue! For reference, line 285 is this:

```
success_result=$(az graph query -q "$graph_success_query" ${(z)mg_option} -o tsv 2>$error_file --query 'data[].id' | sort -u)
```

I haven't been to repro using bash or zsh. @sijday, which shell are you using? (you can verify with `echo $SHELL`).

Something interesting is that your error message says `invalid escape`, but I don't see any escape character in the previous line. @sijday, could you confirm that line 285 of your script looks exactly like the above?

**Comment by sijday** [comment] 2022-02-16 19:39
Hello Jose,
Yes the line is the same in the script I have downloaded. I'm using bash. 
I wondered whether the issue is with a character in one of the variable values.
Thanks,
Simon.

**Comment by sijday** [comment] 2022-02-17 16:51
Here you go. I did also check separately that the vm could access the checklist url to check it wasn't an issue there.
`./checklist_graph.sh --technology=lz --list-categories --debug
DEBUG: Getting checklist from https://raw.githubusercontent.com/Azure/review-checklists/main/checklists/lz_checklist.en.json...
parse error: Invalid escape at line 285, column 436
0: - `

**Comment by dgancedo** [comment] 2022-02-18 13:29
I had the same problem and I've manage to workaround it downloading the lz_checklist.en.json and modifying the regex on lines 285 and 286 from @'^(?:10|127|172\\.(?:1[6-9]|2[0-9]|3[01])|192\\.168)\\..*' to @'^(?:10|127|172\\.(?:1[6-9]|2[0-9]|3[01])|192\\.168)\\.'

**Comment by erjosito** [comment] 2022-02-18 13:58
Ah, that makes it much more clear. The problem is not in the script, but in the actual query documented in the LZ checklist. I have changed the escape characters in the LZ query so that they dont break when being processed. However, please be aware that the queries in the LZ checklist are not validated yet, this is an area where contributions would be highly appreciated.

**Comment by erjosito** [comment] 2022-02-18 14:00
@dgancedo sorry now I see your note. I used `\\\\` in the checklist and that seemed to do the trick for me. Let me check by removing the asterisk...

**Comment by sijday** [comment] 2022-02-18 14:19
@erjosito @dgancedo thanks I’ll give it another try

**Comment by sijday** [comment] 2022-02-24 11:30
> @sijday Ah, that makes it much more clear. The problem is not in the script, but in the actual query documented in the LZ checklist. I have changed the escape characters in the LZ query so that they dont break when being processed. However, please be aware that the queries in the LZ checklist are not validated yet, this is an area where contributions would be highly appreciated.

@erjosito how is it best to contribute graph queries as we refine them?

**Comment by erjosito** [comment] 2022-02-24 11:32
Any contribution would be highly appreciated :-)

**Comment by erjosito** [comment] 2022-02-28 07:55
Closing this now, the original problem seems to be fixed

**Closed by erjosito** 2022-02-28 07:55 UTC
Labels: graph
